version: '3.9'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=trujistorage
      # - MYSQL_DATA_DIR=/var/lib/mysql_custom
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql_custom

  trujistorage:   
    container_name: trujistorage
    restart: always
    build: .
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    depends_on:
      - mysql

  # prisma-studio:
  #   container_name: prisma-studio
  #   build: .  
  #   environment:
  #     - PRISMA_CLIENT_ENGINE_TYPE=binary
  #   ports:
  #     - '5555:5555'
  #   command: npx prisma studio
  #   volumes:
  #     - ./prisma:/app/prisma
  #   depends_on:
  #     - mysql

  # adminer:
  #   container_name: adminer
  #   image: adminer
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - mysql

      
    