apiVersion: apps/v1
kind: Deployment
metadata:
  name: trujistorage-deployment
  labels:
    app: trujistorage
    tipo: "desarrollo"
spec:
  selector:
    matchLabels:
      app: trujistorage
  replicas: 1
  strategy:
    type: RollingUpdate  # Recomendado para producción
    rollingUpdate:       # estrategia de actualización de despliegue de tipo RollingUpdate
      maxUnavailable: 1  # Número máximo de pods que pueden estar no disponibles durante la actualización
      maxSurge: 1        # Número máximo de pods adicionales que pueden ser creados durante la actualización
  minReadySeconds: 2    # Número mínimo de segundos que un pod debe estar listo sin fallar para que se considere listo
  template:
    metadata:
      labels:
        app: trujistorage
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: trujistorage
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
              protocol: TCP

        - name: trujistorage
          image: trujistudios/trujistorage:v2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          livenessProbe: # Es para saber si el contenedor está vivo o muerto
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            # successThreshold: 1 # Se define el número de veces que la sonda debe tener éxito antes de que se considere que el contenedor está vivo
            failureThreshold: 3
          readinessProbe: # Es para saber si el contenedor está listo para recibir tráfico
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 2
            failureThreshold: 3

# ---

# #############
# # SERVICIO  
# #############

# apiVersion: v1
# kind: Service
# metadata:
#   name: trujistorage-svc
# spec:
#   selector:
#     app: trujistorage
#   ports:
#   - port: 80
#     nodePort: 30001
#     protocol: TCP
  
    # targetPort: <Target Port>
