apiVersion: v1
kind: Pod
metadata:
  name: trujistorage-pod
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: trujistorage
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 3306
          protocol: TCP
    - name: storage
      image: trujistudios/trujistorage:v2
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 25
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
  imagePullSecrets:
    - name: midocker
