apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: trujistudios
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=   # admin  (base64)
  MYSQL_DATABASE: dHJ1amlzdG9yYWdl  # trujistorage (base64)
  
# stringData:  # esta linea se usa para que no se codifiquen en base64
#   MYSQL_USER: "Diego"
#   MYSQL_PASSWORD: "trujillo123"
